### ISSUE TITLE
Can you add the “give a like”  functionality for the reply below the forum post?

### ISSUE THREAD

**Issue by bnulhf** [the-open-agent/openagent#108]
Like V2ex, can you add the "thank the replier ( or“give a like” to a floor)" functionality for the reply below the post? In V2ex,  clicks "thank the replier" to a reply below the post, it will refresh to see that this reply has a little red heart mark.
As shown in the figure.
![image](https://user-images.githubusercontent.com/57997507/103649217-0c4e9800-4f99-11eb-8a54-6657233eb0a4.png)
![image](https://user-images.githubusercontent.com/57997507/103649244-1a9cb400-4f99-11eb-9af8-07f32907a0ba.png)

**Comment by oceanlvr** [comment]
Hi,@bnulhf.
I read the existing code. And I found that this feature has been implemented.
I think the reason you can’t see the `thank you` is because you haven’t logged in yet. Please log in and try again.

There is a `Thank you with heart` feature code: [web/src/Reply.js](https://github.com/casbin/casbin-forum/blob/03ba4865c0d3f3ba85c46e823977715a01de5f7c/web/src/main/ReplyBox.js#L280)

And I have already tested in the local environment. 

![image](https://user-images.githubusercontent.com/36698124/104324543-8c897600-5522-11eb-93d5-5c99bb75b120.png)


It also works in online casbin-forum:
![image](https://user-images.githubusercontent.com/36698124/104324637-a7f48100-5522-11eb-9cba-adb8517b2817.png)

**Comment by bnulhf** [comment]
Oh, that's true. I'm sorry I didn't notice. Thank you very much！
